// Defines constant
export const FETCH_USER = 'FETCH_USER';
export const FETCH_RATINGHIST = 'FETCH_RATINGHIST'
export const FETCH_USUBMISSIONS = 'FETCH_USUBMISSIONS'
export const FETCH_CONTESTS = 'FETCH_CONTESTS'